apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: dotnetmicroserviceregistry.azurecr.io/platformservice:latest
          imagePullPolicy: Always
          env:
          - name: PlatformsConn # the application expects to find the sql connection details in this environment variable
            valueFrom:
              secretKeyRef:
                name: mssqlconn # the name of the Kubernetes secret containing the data
                key: PlatformsConn # the key inside the Kubernetes secret containing the data
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666
